# Generated by Django 5.1.2 on 2024-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_activity_timetable_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='special_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_range',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
