# Generated by Django 5.1.2 on 2025-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
